AWSTemplateFormatVersion: '2010-09-09'
Description: Development cloudFormation template for the Service Workbench V2
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  pPrefix:
    Type: String
    Description: Prefix for Lambda function naming
    Default: develop
  pTableName:
    Type: String
    Description: Table name for Aurora DB
    Default: wb_bhargav
  ApiName:
    Type: String
    Default: WorkbenchAPI
    Description: Name of the API Gateway API
  VPCPrefix:
    Type: String
    Default: WorkbenchVPC
    Description: Environment name prefix for VPC resources
  pArtifactsBucketName:
    Type: String
    Default: "service-workbench-artifacts"
    Description: Name of the S3 bucket for artifacts
  pProfileImageBucketName:
    Type: String
    Default: "develop-profile-images"
    Description: Name of the S3 bucket for profile images
  DeploymentTrigger:
    Type: String
    Description: time
  pRAGPrefix:
    Type: String
    Description: rag-prefix
    Default: develop
  SwaggerHash:
    Type: String
    Description: Hash or version to force API Gateway update when swagger.yaml changes
    Default: "v1"

Resources:

  WorkspacesAndSolutionsLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${pPrefix}-workspacesandsolutions-lambda"
      Handler: WorkspacesAndSolutionsLambda.lambda_handler
      Role: !ImportValue WorkspaceLambdaExecutionRole
      Runtime: python3.13
      VpcConfig:
        SubnetIds:
          - Fn::ImportValue:
              Fn::Sub: "${VPCPrefix}-Private-Subnet-1-ID"
          - Fn::ImportValue:
              Fn::Sub: "${VPCPrefix}-Private-Subnet-2-ID"
        SecurityGroupIds:
          - Fn::ImportValue:
              Fn::Sub: "${VPCPrefix}-Lambda-SG-ID"
      Environment:
        Variables:
          ACTIVITY_LOGS_TABLE: !Sub Workbench-develop-ActivityLogsTable
          SOLUTIONS_TABLE: !Sub Workbench-${pPrefix}-SolutionsTable
          TEMPLATES_TABLE: !Sub Workbench-${pPrefix}-TemplatesTable
          WORKSPACES_TABLE: !Sub Workbench-${pPrefix}-WorkspacesTable
          EXECUTIONS_TABLE: !Sub Workbench-${pPrefix}-SolutionExecutionsTable
          DATASOURCES_TABLE: !Sub Workbench-${pPrefix}-DatasourcesTable
          ROLES_TABLE: !Sub Workbench-${pPrefix}-RolesTable
          RESOURCE_ACCESS_TABLE: !Sub Workbench-${pPrefix}-ResourceAccessTable
      Code:
        S3Bucket: service-workbench-artifacts
        S3Key: lambda/workspacesandsolutionslambda/WorkspacesAndSolutionsLambda.zip
      Layers:
        - !ImportValue ServiceWorkbenchLambdaLayer
      Tags:
        - Key: Name
          Value: "WorkbenchV2"
  
  # S3 Bucket for artifacts
  ProfileImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref pProfileImageBucketName
      AccessControl: PublicRead
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: "WorkbenchV2"
  
  ProfileImageBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ProfileImageBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${ProfileImageBucket.Arn}/*"

  # API Gateway
  WorkbenchApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "${pPrefix}-${ApiName}"
      StageName: prod
      DefinitionUri:
        Bucket: service-workbench-artifacts
        Key: develop/swagger.yaml
      EndpointConfiguration: REGIONAL
      TracingEnabled: true
      AlwaysDeploy: true

  WorkspaceLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref WorkspacesAndSolutionsLambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WorkbenchApi}/*/*/*'

  # remove WorkbenchApiDeployment and WorkbenchApiStage resources ...

  WorkspacesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'Workbench-${pPrefix}-WorkspacesTable'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: WorkspaceId
          AttributeType: S
        - AttributeName: WorkspaceName
          AttributeType: S
        - AttributeName: CreatedBy
          AttributeType: S
      KeySchema:
        - AttributeName: WorkspaceId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: CreatedBy-index
          KeySchema:
            - AttributeName: CreatedBy
              KeyType: HASH
            - AttributeName: WorkspaceName
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Name
          Value: "WorkbenchV2"

  SolutionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'Workbench-${pPrefix}-SolutionsTable'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: WorkspaceId
          AttributeType: S
        - AttributeName: SolutionId
          AttributeType: S
      KeySchema:
        - AttributeName: WorkspaceId
          KeyType: HASH
        - AttributeName: SolutionId
          KeyType: RANGE
      Tags:
        - Key: Name
          Value: "WorkbenchV2"

  DatasourcesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'Workbench-${pPrefix}-DatasourcesTable'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: DatasourceId
          AttributeType: S
      KeySchema:
        - AttributeName: DatasourceId
          KeyType: HASH
      Tags:
        - Key: Name
          Value: "WorkbenchV2"

  ResourceAccessTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'Workbench-${pPrefix}-ResourceAccessTable'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
        - AttributeName: AccessKey
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
        - AttributeName: AccessKey
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: AccessKey-Index
          KeySchema:
            - AttributeName: AccessKey
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Name
          Value: "WorkbenchV2"

  SolutionExecutionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'Workbench-${pPrefix}-SolutionExecutionsTable'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: SolutionId
          AttributeType: S
        - AttributeName: ExecutionId
          AttributeType: S
      KeySchema:
        - AttributeName: SolutionId
          KeyType: HASH
        - AttributeName: ExecutionId
          KeyType: RANGE
      Tags:
        - Key: Name
          Value: "WorkbenchV2"

  TemplatesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'Workbench-${pPrefix}-TemplatesTable'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: SolutionId
          AttributeType: S
        - AttributeName: Version
          AttributeType: S
      KeySchema:
        - AttributeName: SolutionId
          KeyType: HASH
        - AttributeName: Version
          KeyType: RANGE
      Tags:
        - Key: Name
          Value: "WorkbenchV2"

  RolesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'Workbench-${pPrefix}-RolesTable'
      AttributeDefinitions:
        - AttributeName: Role
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: Role
          KeyType: HASH
      Tags:
        - Key: Name
          Value: "WorkbenchV2"

  RBACCustomResourceLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${pPrefix}-RBACCustomResource"
      Handler: lambda_function.lambda_handler
      Role: !ImportValue WorkbenchCustomResourceLambdaExecutionRole
      Runtime: python3.12
      Timeout: 900
      Layers:
        - !ImportValue ServiceWorkbenchLambdaLayer
      Code:
        S3Bucket: service-workbench-artifacts
        S3Key: lambda/rbaccustomresource/rbac_custom_resource.zip
      Tags:
        - Key: Name
          Value: "WorkbenchV2"

  RBACCustomResource:
    Type: Custom::RBACCustomResource
    DependsOn:
      - RBACCustomResourceLambda
    Properties:
      ServiceToken: !GetAtt RBACCustomResourceLambda.Arn
      RolesTable: !Sub "Workbench-${pPrefix}-RolesTable"
      Changesetflag: "2025-07-02"
      Tags:
        - Key: Name
          Value: "WorkbenchV2"

# Lambdas
  RolesLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${pPrefix}-RolesLambdaFunction"
      Handler: lambda_function.lambda_handler
      Role: !ImportValue RolesLambdaFunctionRole
      Runtime: python3.12
      Timeout: 900
      Environment:
        Variables:
          ROLES_TABLE: !Sub "Workbench-${pPrefix}-RolesTable"
      VpcConfig:
        SubnetIds:
          - Fn::ImportValue:
              Fn::Sub: "${VPCPrefix}-Private-Subnet-1-ID"
          - Fn::ImportValue:
              Fn::Sub: "${VPCPrefix}-Private-Subnet-2-ID"
        SecurityGroupIds:
          - Fn::ImportValue:
              Fn::Sub: "${VPCPrefix}-Lambda-SG-ID"
      Layers:
        - !ImportValue ServiceWorkbenchLambdaLayer
      Code:
        S3Bucket: service-workbench-artifacts
        S3Key: lambda/roles/roles_lambda.zip
      Tags:
        - Key: Name
          Value: "WorkbenchV2"

  UsersLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${pPrefix}-UsersLambdaFunction"
      Handler: lambda_function.lambda_handler
      Role: !ImportValue UserExecutionRoleARN
      Runtime: python3.12
      Timeout: 900
      Environment:
        Variables:
          USER_TABLE_NAME: !ImportValue UsersTableName
          PROFILE_IMAGE_BUCKET: !Ref ProfileImageBucket
      VpcConfig:
        SubnetIds:
          - Fn::ImportValue:
              Fn::Sub: "${VPCPrefix}-Private-Subnet-1-ID"
          - Fn::ImportValue:
              Fn::Sub: "${VPCPrefix}-Private-Subnet-2-ID"
        SecurityGroupIds:
          - Fn::ImportValue:
              Fn::Sub: "${VPCPrefix}-Lambda-SG-ID"
      Layers:
        - !ImportValue ServiceWorkbenchLambdaLayer
      Code:
        S3Bucket: service-workbench-artifacts
        S3Key: lambda/workbenchuserslambda/WorkbenchUsersLambda.zip
      Tags:
        - Key: Name
          Value: "WorkbenchV2"

# Lambda Permission for API Gateway to invoke Roles Lambda
  RolesLambdaFunctionInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref RolesLambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WorkbenchApi}/*/*/*
     
  UsersLambdaFunctionInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref UsersLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WorkbenchApi}/*/*/*

  VectorKnowledgeBase:
    Type: AWS::Bedrock::KnowledgeBase
    Properties:
      Name: !Sub "${pPrefix}-KnowledgeBase"
      Description: "Stores vectorized data in OpenSearch"
      RoleArn: !ImportValue "develop-CustomResourceLambdaRoleARN"
      StorageConfiguration:
        Type: OPENSEARCH_MANAGED_CLUSTER
        OpensearchManagedClusterConfiguration:
          DomainArn: !ImportValue "develop-OpenSearchDBArn"
          DomainEndpoint: !Join
            - ""
            - - "https://"
              - !ImportValue "develop-OpenSearchEndpoint"
          FieldMapping: 
            VectorField: "bedrock-knowledge-base-default-vector"  
            TextField: "AMAZON_BEDROCK_TEXT_CHUNK"               
            MetadataField: "AMAZON_BEDROCK_METADATA"  
          VectorIndexName: !Sub "${pPrefix}_vector_index"
      KnowledgeBaseConfiguration:
        Type: VECTOR
        VectorKnowledgeBaseConfiguration:
          EmbeddingModelArn: !Sub "arn:aws:bedrock:${AWS::Region}::foundation-model/amazon.titan-embed-text-v2:0"

  AuroraKnowledgeBase:
    Type: AWS::Bedrock::KnowledgeBase
    Properties:
      Name: !Sub "${pPrefix}-AuroraKB"
      Description: "Knowledge base using Aurora PostgreSQL"
      RoleArn: !ImportValue "develop-CustomResourceLambdaRoleARN"
      KnowledgeBaseConfiguration:
        Type: "VECTOR"
        VectorKnowledgeBaseConfiguration:
          EmbeddingModelArn: "arn:aws:bedrock:us-east-1::foundation-model/amazon.titan-embed-text-v2:0"
      StorageConfiguration:
        Type: "RDS"
        RdsConfiguration:
          ResourceArn: !ImportValue "develop-AuroraDBClusterARN"
          CredentialsSecretArn: !ImportValue "develop-AuroraDBSecretARN"
          DatabaseName: !ImportValue "develop-AuroraDBName"
          TableName: !Sub "${pRAGPrefix}_aurora_table" 
          FieldMapping:
            VectorField: "embedding"
            TextField: "content"
            MetadataField: "metadata"
            PrimaryKeyField: "id" 

  WorkbenchLambdaAuthorizerInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !ImportValue LambdaAuthorizerFunctionName
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WorkbenchApi}/*

Outputs:

  WorkspaceLambdaFunctionName:
    Description: Name of the Workspace Lambda function
    Value: !Ref WorkspacesAndSolutionsLambdaFunction

  ApiUrl:
    Description: "Invoke URL for the deployed API"
    Value: !Sub "https://${WorkbenchApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
