---
AWSTemplateFormatVersion: '2010-09-09'
Description: Simple DynamoDB Table Deployment

Parameters:
  pApplicationPrefix:
    Type: String
    Default: simple
    Description: Prefix for the application resources

Resources:
  rSimpleDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${pApplicationPrefix}-SimpleTable"
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
